[workspace]
members = ["aurora-api", "aurora-proto","aurora-config"]

resolver = "2"
[workspace.package]
version = "0.1.0"
edition = "2021"
description = "AuroraPlan is your go-to scheduling and planning tool. It helps you manage your tasks and appointments effortlessly. With AuroraPlan, you can stay organized, save time, and enjoy a stress-free schedule."
repository = "https://github.com/heheshang/AuroraPlan"
keywords = [
    "aurora",
    "plan",
    "schedule",
    "task",
    "calendar",
    "planner",
    "organize",
    "management",
    "productivity",
    "time",
    "free",
    "project",
]
categories = ["science"]
license = "MIT OR Apache-2.0"


[workspace.dependencies]
tokio = { version = "1.33.0", features = ["full"] }
axum = { version = "0.6.20", features = ["full"] }
dotenvy = "0.15.7"
config = { version = "0.13.3", features = ["toml"] }
serde_derive = "1.0.188"
serde = { version = "1.0.188", features = ["derive"] }


[workspace.dev-dependencies]
prost-build = { version = "0.11.6" }
tonic-build = "0.9.2"
proto-builder-trait = "0.5.1"

[workspace.build-dependencies]
prost-build = { version = "0.11.6" }
tonic-build = "0.9.2"
proto-builder-trait = "0.5.1"


[profile.release-with-debug]
inherits = "release"
debug = true
