//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "qrtz_job_details")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sched_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub job_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub job_group: String,
    pub description: Option<String>,
    pub job_class_name: String,
    pub is_durable: bool,
    pub is_nonconcurrent: bool,
    pub is_update_data: bool,
    pub requests_recovery: bool,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub job_data: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
