//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_error_command")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub command_type: Option<i32>,
    pub process_definition_code: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub command_param: Option<String>,
    pub task_depend_type: Option<i32>,
    pub failure_strategy: Option<i32>,
    pub warning_type: Option<i32>,
    pub warning_group_id: Option<i32>,
    pub schedule_time: Option<DateTime>,
    pub start_time: Option<DateTime>,
    pub executor_id: Option<i32>,
    pub update_time: Option<DateTime>,
    pub process_instance_priority: Option<i32>,
    pub worker_group: Option<String>,
    pub tenant_code: Option<String>,
    pub environment_code: Option<i64>,
    pub dry_run: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    pub process_instance_id: Option<i32>,
    pub process_definition_version: Option<i32>,
    pub test_flag: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
