//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_resources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub alias: Option<String>,
    pub file_name: Option<String>,
    pub description: Option<String>,
    pub user_id: Option<i32>,
    pub r#type: Option<i32>,
    pub size: Option<i64>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub pid: Option<i32>,
    pub full_name: Option<String>,
    pub is_directory: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
