//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_schedules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub process_definition_code: i64,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub timezone_id: Option<String>,
    pub crontab: String,
    pub failure_strategy: i32,
    pub user_id: i32,
    pub release_state: i32,
    pub warning_type: i32,
    pub warning_group_id: Option<i32>,
    pub process_instance_priority: Option<i32>,
    pub worker_group: Option<String>,
    pub tenant_code: Option<String>,
    pub environment_code: Option<i64>,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
