//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_dq_rule_input_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub field: Option<String>,
    pub r#type: Option<String>,
    pub title: Option<String>,
    pub value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub options: Option<String>,
    pub placeholder: Option<String>,
    pub option_source_type: Option<i32>,
    pub value_type: Option<i32>,
    pub input_type: Option<i32>,
    pub is_show: Option<i16>,
    pub can_edit: Option<i16>,
    pub is_emit: Option<i16>,
    pub is_validate: Option<i16>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
