//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_relation_rule_input_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub rule_id: Option<i32>,
    pub rule_input_entry_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub values_map: Option<String>,
    pub index: Option<i32>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
