//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_relation_process_instance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub parent_process_instance_id: Option<i32>,
    pub parent_task_instance_id: Option<i32>,
    pub process_instance_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
