//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_alert")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: Option<String>,
    pub sign: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub alert_status: Option<i32>,
    pub warning_type: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub log: Option<String>,
    pub alertgroup_id: Option<i32>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub project_code: Option<i64>,
    pub process_definition_code: Option<i64>,
    pub process_instance_id: Option<i32>,
    pub alert_type: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
