//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_dq_rule_execute_sql")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub index: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sql: Option<String>,
    pub table_alias: Option<String>,
    pub r#type: Option<i32>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub is_error_output_sql: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
